### ISSUE TITLE
Hover buttons

### ISSUE THREAD

**Issue by AlexScheaua** [MarianBulumac/Proiect-Final#2]
In today`s applications all the buttons come with hovering effects.
Lets add some hover to the buttons on our app, so they will be more dynamic.
---
PS: I reckon you will have some problems with doing that.
Try to check what are the differences between ID and Class selectors.
https://css-tricks.com/the-difference-between-id-and-class

**Comment by MarianBulumac** [comment]
I think it was better to make a separate  css file for this task.

**Comment by AlexScheaua** [comment]
It`s no need for a separate css file just for button hovering.
